### ISSUE TITLE
Still maintaining this?

### ISSUE THREAD

**Issue by abulte** [swalladge/snsrv#1]
Hi,

Are you still maintaining this repository / using this tool? I find it handy as a base tool for my implementation, thanks.

I started a fork here https://github.com/abulte/snsrv, if you are interested I can submit PRs. I have a few bugfix, code styling and tests for now. I'll probably go much deeper into refactoring if I keep using this tool.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by swalladge** [comment]
Yep, I'm still going to be maintaining it. Haven't had much time in the last month due to uni, but I'm hoping to do some more work on it soon.

I'd definitely be interested in any pull requests! Feel free to submit PRs, open issues here, etc. I'll aim to review them/comment/accept/merge as soon as possible.
There'll probably be lots of refactoring needed yeah... quick and messy experiment with flask that turned into a project.
I'm hoping to turn it into a fully working stable implementation of the simplenote third party api so it can be used with current apps (with modification to allow connecting to alternate servers) and future apps... 
It's still in early stages though - I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not, and still working out how to store notes and tag data most efficiently with sqlite. 

Just out of interest, what are you using this for currently? As far as I know, it's only my fork of sncli (https://github.com/swalladge/sncli) which can actually connect to it.

**Comment by abulte** [comment]
Ok cool, I'll send you some PRs and maybe we can move this thing forward.

I came to use this project because I wanted my own implementation of SimpleNote, or something equivalent. I'm building a mobile app client for it: https://bitbucket.org/abulte/nosweatnote, already basically working ;-).

I like the idea of standardizing on a well know robust API, such as SimpleNote's one should be.

**Comment by abulte** [comment]
> I'm not sure yet whether to split out the webapp/website part of it into another project and keep this as just the api or not

I would advise in favor of two separate projects. This one should be a client independent server implementation IMHO.

**Comment by swalladge** [comment]
Nice! :)
