### ISSUE TITLE
Use Flask-SQLAlchemy?

### ISSUE THREAD

**Issue by abulte** [swalladge/snsrv#6]
Do you have anything against using http://flask-sqlalchemy.pocoo.org instead of a custom ORM? This will probably be my next refactoring step, after adding some more tests coverage.

**Comment by swalladge** [comment]
No... I had previously implemented my own because I wanted to experiment with raw queries and less abstraction. Never actually used something like sqlalchemy. Would probably tidy up the database backend code a lot though. 
I guess the real question is would it be worth pulling in another dependency for this? I was also hoping to support mongodb down the track, which sqlalchemy won't be able to handle. (On the plus side it would make it easier to connect to a different database engine rather than just sqlite)

**Comment by abulte** [comment]
Yes it's totally worth it IMHO. You get clean, secure and cross-database code basically for free. As for the support of MongoDB, that's something that can be added along the way, but unplugging sqlalchemy if needed. You would have to duplicate the models though.

**Comment by swalladge** [comment]
Ok, sounds good. Like I said previously though, I don't have much experience with all this - this started off as an experiment to play with implementing all this on a lower level. 

I'll have plenty of time to look into it in about 4 weeks, but in the meantime you're welcome to do as much refactoring as you like. I can always create multiple branches here for development as well if needed.

I'm guessing the user authentication part will have to be refactored to work with sqlalchemy as well, since that's a custom implementation too.

I'm kinda wondering whether it would be better just to start from scratch with something like Django (which I'm wanting to learn anyway), which  has fancy user auth, database management, etc. all built in....?

**Comment by swalladge** [comment]
I'm planning on working seriously on this project over the next two weeks. My plan is to port the code over to tornado and sqlalchemy (I've done a few projects with tornado before, and looked into sqlalchemy between now and my previous comment). Hopefully this will result in neater and more maintainable code.

**Comment by swalladge** [comment]
sqlalchemy is now in use
